{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains all types with cyclic dependencies (between each other or to itself)
module Binance.TypeAlias where

import qualified Binance.Common
import {-# SOURCE #-} Binance.Types.BookTicker
import {-# SOURCE #-} Binance.Types.PriceTicker
import {-# SOURCE #-} Binance.Types.Ticker
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines an alias for the schema located at @components.schemas.tickerList@ in the specification.
type TickerList = [Ticker]

-- | Defines an alias for the schema located at @components.schemas.priceTickerList@ in the specification.
type PriceTickerList = [PriceTicker]

-- | Defines an alias for the schema located at @components.schemas.bookTickerList@ in the specification.
type BookTickerList = [BookTicker]
