module Binance.Types.CanceledMarginOrderDetail where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data CanceledMarginOrderDetail
instance Show CanceledMarginOrderDetail
instance Eq CanceledMarginOrderDetail
instance FromJSON CanceledMarginOrderDetail
instance ToJSON CanceledMarginOrderDetail
