module Binance.Types.IsolatedMarginAccountInfo where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data IsolatedMarginAccountInfo
instance Show IsolatedMarginAccountInfo
instance Eq IsolatedMarginAccountInfo
instance FromJSON IsolatedMarginAccountInfo
instance ToJSON IsolatedMarginAccountInfo
data IsolatedMarginAccountInfoAssets
instance Show IsolatedMarginAccountInfoAssets
instance Eq IsolatedMarginAccountInfoAssets
instance FromJSON IsolatedMarginAccountInfoAssets
instance ToJSON IsolatedMarginAccountInfoAssets
data IsolatedMarginAccountInfoAssetsBaseAsset
instance Show IsolatedMarginAccountInfoAssetsBaseAsset
instance Eq IsolatedMarginAccountInfoAssetsBaseAsset
instance FromJSON IsolatedMarginAccountInfoAssetsBaseAsset
instance ToJSON IsolatedMarginAccountInfoAssetsBaseAsset
data IsolatedMarginAccountInfoAssetsQuoteAsset
instance Show IsolatedMarginAccountInfoAssetsQuoteAsset
instance Eq IsolatedMarginAccountInfoAssetsQuoteAsset
instance FromJSON IsolatedMarginAccountInfoAssetsQuoteAsset
instance ToJSON IsolatedMarginAccountInfoAssetsQuoteAsset
