module Binance.Types.SavingsFixedActivityRedemptionRecord where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data SavingsFixedActivityRedemptionRecordItem
instance Show SavingsFixedActivityRedemptionRecordItem
instance Eq SavingsFixedActivityRedemptionRecordItem
instance FromJSON SavingsFixedActivityRedemptionRecordItem
instance ToJSON SavingsFixedActivityRedemptionRecordItem
type SavingsFixedActivityRedemptionRecord = [SavingsFixedActivityRedemptionRecordItem]
