module Binance.Types.SavingsFlexiblePurchaseRecord where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data SavingsFlexiblePurchaseRecordItem
instance Show SavingsFlexiblePurchaseRecordItem
instance Eq SavingsFlexiblePurchaseRecordItem
instance FromJSON SavingsFlexiblePurchaseRecordItem
instance ToJSON SavingsFlexiblePurchaseRecordItem
type SavingsFlexiblePurchaseRecord = [SavingsFlexiblePurchaseRecordItem]
