module Binance.Types.SubAccountUSDTFuturesPositionRisk where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data SubAccountUSDTFuturesPositionRisk
instance Show SubAccountUSDTFuturesPositionRisk
instance Eq SubAccountUSDTFuturesPositionRisk
instance FromJSON SubAccountUSDTFuturesPositionRisk
instance ToJSON SubAccountUSDTFuturesPositionRisk
data SubAccountUSDTFuturesPositionRiskFuturePositionRiskVos
instance Show SubAccountUSDTFuturesPositionRiskFuturePositionRiskVos
instance Eq SubAccountUSDTFuturesPositionRiskFuturePositionRiskVos
instance FromJSON SubAccountUSDTFuturesPositionRiskFuturePositionRiskVos
instance ToJSON SubAccountUSDTFuturesPositionRiskFuturePositionRiskVos
