module Binance.Types.SubAccountUSDTFuturesDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data SubAccountUSDTFuturesDetails
instance Show SubAccountUSDTFuturesDetails
instance Eq SubAccountUSDTFuturesDetails
instance FromJSON SubAccountUSDTFuturesDetails
instance ToJSON SubAccountUSDTFuturesDetails
data SubAccountUSDTFuturesDetailsFutureAccountResp
instance Show SubAccountUSDTFuturesDetailsFutureAccountResp
instance Eq SubAccountUSDTFuturesDetailsFutureAccountResp
instance FromJSON SubAccountUSDTFuturesDetailsFutureAccountResp
instance ToJSON SubAccountUSDTFuturesDetailsFutureAccountResp
data SubAccountUSDTFuturesDetailsFutureAccountRespAssets
instance Show SubAccountUSDTFuturesDetailsFutureAccountRespAssets
instance Eq SubAccountUSDTFuturesDetailsFutureAccountRespAssets
instance FromJSON SubAccountUSDTFuturesDetailsFutureAccountRespAssets
instance ToJSON SubAccountUSDTFuturesDetailsFutureAccountRespAssets
