module Binance.Types.SubAccountCOINFuturesPositionRisk where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data SubAccountCOINFuturesPositionRisk
instance Show SubAccountCOINFuturesPositionRisk
instance Eq SubAccountCOINFuturesPositionRisk
instance FromJSON SubAccountCOINFuturesPositionRisk
instance ToJSON SubAccountCOINFuturesPositionRisk
data SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
instance Show SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
instance Eq SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
instance FromJSON SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
instance ToJSON SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
