module Binance.Types.SubAccountCOINFuturesSummary where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data SubAccountCOINFuturesSummary
instance Show SubAccountCOINFuturesSummary
instance Eq SubAccountCOINFuturesSummary
instance FromJSON SubAccountCOINFuturesSummary
instance ToJSON SubAccountCOINFuturesSummary
data SubAccountCOINFuturesSummaryDeliveryAccountSummaryResp
instance Show SubAccountCOINFuturesSummaryDeliveryAccountSummaryResp
instance Eq SubAccountCOINFuturesSummaryDeliveryAccountSummaryResp
instance FromJSON SubAccountCOINFuturesSummaryDeliveryAccountSummaryResp
instance ToJSON SubAccountCOINFuturesSummaryDeliveryAccountSummaryResp
data SubAccountCOINFuturesSummaryDeliveryAccountSummaryRespSubAccountList
instance Show SubAccountCOINFuturesSummaryDeliveryAccountSummaryRespSubAccountList
instance Eq SubAccountCOINFuturesSummaryDeliveryAccountSummaryRespSubAccountList
instance FromJSON SubAccountCOINFuturesSummaryDeliveryAccountSummaryRespSubAccountList
instance ToJSON SubAccountCOINFuturesSummaryDeliveryAccountSummaryRespSubAccountList
