module Binance.Types.SubAccountUSDTFuturesSummary where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Binance.Common
data SubAccountUSDTFuturesSummary
instance Show SubAccountUSDTFuturesSummary
instance Eq SubAccountUSDTFuturesSummary
instance FromJSON SubAccountUSDTFuturesSummary
instance ToJSON SubAccountUSDTFuturesSummary
data SubAccountUSDTFuturesSummaryFutureAccountSummaryResp
instance Show SubAccountUSDTFuturesSummaryFutureAccountSummaryResp
instance Eq SubAccountUSDTFuturesSummaryFutureAccountSummaryResp
instance FromJSON SubAccountUSDTFuturesSummaryFutureAccountSummaryResp
instance ToJSON SubAccountUSDTFuturesSummaryFutureAccountSummaryResp
data SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
instance Show SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
instance Eq SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
instance FromJSON SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
instance ToJSON SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
