{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the different functions to run the operation getSapiV1MarginIsolatedMarginTier
module Binance.Operations.GetSapiV1MarginIsolatedMarginTier where

import qualified Binance.Common
import Binance.Types
import qualified Control.Monad.Fail
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | > GET /sapi/v1/margin/isolatedMarginTier
--
-- Get isolated margin tier data collection with any tier as https:\/\/www.binance.com\/en\/margin-data
--
-- Weight(IP): 1
getSapiV1MarginIsolatedMarginTier ::
  forall m.
  Binance.Common.MonadHTTP m =>
  -- | Contains all available parameters of this operation (query and path parameters)
  GetSapiV1MarginIsolatedMarginTierParameters ->
  -- | Monadic computation which returns the result of the operation
  Binance.Common.ClientT m (Network.HTTP.Client.Types.Response GetSapiV1MarginIsolatedMarginTierResponse)
getSapiV1MarginIsolatedMarginTier parameters =
  GHC.Base.fmap
    ( \response_0 ->
        GHC.Base.fmap
          ( Data.Either.either GetSapiV1MarginIsolatedMarginTierResponseError GHC.Base.id
              GHC.Base.. ( \response body ->
                             if
                                 | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                   GetSapiV1MarginIsolatedMarginTierResponse200
                                     Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                          Data.Either.Either
                                                            GHC.Base.String
                                                            ([GetSapiV1MarginIsolatedMarginTierResponseBody200])
                                                      )
                                 | (\status_2 -> Network.HTTP.Types.Status.statusCode status_2 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                   GetSapiV1MarginIsolatedMarginTierResponse400
                                     Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                          Data.Either.Either
                                                            GHC.Base.String
                                                            Error
                                                      )
                                 | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 401) (Network.HTTP.Client.Types.responseStatus response) ->
                                   GetSapiV1MarginIsolatedMarginTierResponse401
                                     Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                          Data.Either.Either
                                                            GHC.Base.String
                                                            Error
                                                      )
                                 | GHC.Base.otherwise -> Data.Either.Left "Missing default response type"
                         )
                response_0
          )
          response_0
    )
    ( Binance.Common.doCallWithConfigurationM
        (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET")
        (Data.Text.pack "/sapi/v1/margin/isolatedMarginTier")
        [ Binance.Common.QueryParameter (Data.Text.pack "symbol") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQuerySymbol parameters)) (Data.Text.pack "form") GHC.Types.False,
          Binance.Common.QueryParameter (Data.Text.pack "tier") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> getSapiV1MarginIsolatedMarginTierParametersQueryTier parameters) (Data.Text.pack "form") GHC.Types.False,
          Binance.Common.QueryParameter (Data.Text.pack "recvWindow") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> getSapiV1MarginIsolatedMarginTierParametersQueryRecvWindow parameters) (Data.Text.pack "form") GHC.Types.False,
          Binance.Common.QueryParameter (Data.Text.pack "timestamp") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp parameters)) (Data.Text.pack "form") GHC.Types.False,
          Binance.Common.QueryParameter (Data.Text.pack "signature") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQuerySignature parameters)) (Data.Text.pack "form") GHC.Types.False
        ]
    )

-- | Defines the object schema located at @paths.\/sapi\/v1\/margin\/isolatedMarginTier.GET.parameters@ in the specification.
data GetSapiV1MarginIsolatedMarginTierParameters = GetSapiV1MarginIsolatedMarginTierParameters
  { -- | queryRecvWindow: Represents the parameter named \'recvWindow\'
    --
    -- The value cannot be greater than 60000
    getSapiV1MarginIsolatedMarginTierParametersQueryRecvWindow :: (GHC.Maybe.Maybe GHC.Int.Int64),
    -- | querySignature: Represents the parameter named \'signature\'
    --
    -- Signature
    getSapiV1MarginIsolatedMarginTierParametersQuerySignature :: Data.Text.Internal.Text,
    -- | querySymbol: Represents the parameter named \'symbol\'
    --
    -- Trading symbol, e.g. BNBUSDT
    getSapiV1MarginIsolatedMarginTierParametersQuerySymbol :: Data.Text.Internal.Text,
    -- | queryTier: Represents the parameter named \'tier\'
    --
    -- All margin tier data will be returned if tier is omitted
    getSapiV1MarginIsolatedMarginTierParametersQueryTier :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | queryTimestamp: Represents the parameter named \'timestamp\'
    --
    -- UTC timestamp in ms
    getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp :: GHC.Int.Int64
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON GetSapiV1MarginIsolatedMarginTierParameters where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryRecvWindow" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierParametersQueryRecvWindow obj) : ["querySignature" Data.Aeson.Types.ToJSON..= getSapiV1MarginIsolatedMarginTierParametersQuerySignature obj] : ["querySymbol" Data.Aeson.Types.ToJSON..= getSapiV1MarginIsolatedMarginTierParametersQuerySymbol obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryTier" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierParametersQueryTier obj) : ["queryTimestamp" Data.Aeson.Types.ToJSON..= getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryRecvWindow" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierParametersQueryRecvWindow obj) : ["querySignature" Data.Aeson.Types.ToJSON..= getSapiV1MarginIsolatedMarginTierParametersQuerySignature obj] : ["querySymbol" Data.Aeson.Types.ToJSON..= getSapiV1MarginIsolatedMarginTierParametersQuerySymbol obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("queryTier" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierParametersQueryTier obj) : ["queryTimestamp" Data.Aeson.Types.ToJSON..= getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON GetSapiV1MarginIsolatedMarginTierParameters where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "GetSapiV1MarginIsolatedMarginTierParameters" (\obj -> ((((GHC.Base.pure GetSapiV1MarginIsolatedMarginTierParameters GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryRecvWindow")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "querySignature")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "querySymbol")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "queryTier")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "queryTimestamp"))

-- | Create a new 'GetSapiV1MarginIsolatedMarginTierParameters' with all required fields.
mkGetSapiV1MarginIsolatedMarginTierParameters ::
  -- | 'getSapiV1MarginIsolatedMarginTierParametersQuerySignature'
  Data.Text.Internal.Text ->
  -- | 'getSapiV1MarginIsolatedMarginTierParametersQuerySymbol'
  Data.Text.Internal.Text ->
  -- | 'getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp'
  GHC.Int.Int64 ->
  GetSapiV1MarginIsolatedMarginTierParameters
mkGetSapiV1MarginIsolatedMarginTierParameters getSapiV1MarginIsolatedMarginTierParametersQuerySignature getSapiV1MarginIsolatedMarginTierParametersQuerySymbol getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp =
  GetSapiV1MarginIsolatedMarginTierParameters
    { getSapiV1MarginIsolatedMarginTierParametersQueryRecvWindow = GHC.Maybe.Nothing,
      getSapiV1MarginIsolatedMarginTierParametersQuerySignature = getSapiV1MarginIsolatedMarginTierParametersQuerySignature,
      getSapiV1MarginIsolatedMarginTierParametersQuerySymbol = getSapiV1MarginIsolatedMarginTierParametersQuerySymbol,
      getSapiV1MarginIsolatedMarginTierParametersQueryTier = GHC.Maybe.Nothing,
      getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp = getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp
    }

-- | Represents a response of the operation 'getSapiV1MarginIsolatedMarginTier'.
--
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'GetSapiV1MarginIsolatedMarginTierResponseError' is used.
data GetSapiV1MarginIsolatedMarginTierResponse
  = -- | Means either no matching case available or a parse error
    GetSapiV1MarginIsolatedMarginTierResponseError GHC.Base.String
  | -- | Isolated Margin Tier Data
    GetSapiV1MarginIsolatedMarginTierResponse200 ([GetSapiV1MarginIsolatedMarginTierResponseBody200])
  | -- | Bad Request
    GetSapiV1MarginIsolatedMarginTierResponse400 Error
  | -- | Unauthorized Request
    GetSapiV1MarginIsolatedMarginTierResponse401 Error
  deriving (GHC.Show.Show, GHC.Classes.Eq)

-- | Defines the object schema located at @paths.\/sapi\/v1\/margin\/isolatedMarginTier.GET.responses.200.content.application\/json.schema.items@ in the specification.
data GetSapiV1MarginIsolatedMarginTierResponseBody200 = GetSapiV1MarginIsolatedMarginTierResponseBody200
  { -- | baseAssetMaxBorrowable
    getSapiV1MarginIsolatedMarginTierResponseBody200BaseAssetMaxBorrowable :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | effectiveMultiple
    getSapiV1MarginIsolatedMarginTierResponseBody200EffectiveMultiple :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | initialRiskRatio
    getSapiV1MarginIsolatedMarginTierResponseBody200InitialRiskRatio :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | liquidationRiskRatio
    getSapiV1MarginIsolatedMarginTierResponseBody200LiquidationRiskRatio :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | quoteAssetMaxBorrowable
    getSapiV1MarginIsolatedMarginTierResponseBody200QuoteAssetMaxBorrowable :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | symbol
    getSapiV1MarginIsolatedMarginTierResponseBody200Symbol :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | tier
    getSapiV1MarginIsolatedMarginTierResponseBody200Tier :: (GHC.Maybe.Maybe GHC.Int.Int32)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON GetSapiV1MarginIsolatedMarginTierResponseBody200 where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("baseAssetMaxBorrowable" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200BaseAssetMaxBorrowable obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("effectiveMultiple" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200EffectiveMultiple obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("initialRiskRatio" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200InitialRiskRatio obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("liquidationRiskRatio" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200LiquidationRiskRatio obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("quoteAssetMaxBorrowable" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200QuoteAssetMaxBorrowable obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("symbol" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200Symbol obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("tier" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200Tier obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("baseAssetMaxBorrowable" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200BaseAssetMaxBorrowable obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("effectiveMultiple" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200EffectiveMultiple obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("initialRiskRatio" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200InitialRiskRatio obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("liquidationRiskRatio" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200LiquidationRiskRatio obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("quoteAssetMaxBorrowable" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200QuoteAssetMaxBorrowable obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("symbol" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200Symbol obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("tier" Data.Aeson.Types.ToJSON..=)) (getSapiV1MarginIsolatedMarginTierResponseBody200Tier obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON GetSapiV1MarginIsolatedMarginTierResponseBody200 where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "GetSapiV1MarginIsolatedMarginTierResponseBody200" (\obj -> ((((((GHC.Base.pure GetSapiV1MarginIsolatedMarginTierResponseBody200 GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "baseAssetMaxBorrowable")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "effectiveMultiple")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "initialRiskRatio")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "liquidationRiskRatio")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "quoteAssetMaxBorrowable")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "symbol")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tier"))

-- | Create a new 'GetSapiV1MarginIsolatedMarginTierResponseBody200' with all required fields.
mkGetSapiV1MarginIsolatedMarginTierResponseBody200 :: GetSapiV1MarginIsolatedMarginTierResponseBody200
mkGetSapiV1MarginIsolatedMarginTierResponseBody200 =
  GetSapiV1MarginIsolatedMarginTierResponseBody200
    { getSapiV1MarginIsolatedMarginTierResponseBody200BaseAssetMaxBorrowable = GHC.Maybe.Nothing,
      getSapiV1MarginIsolatedMarginTierResponseBody200EffectiveMultiple = GHC.Maybe.Nothing,
      getSapiV1MarginIsolatedMarginTierResponseBody200InitialRiskRatio = GHC.Maybe.Nothing,
      getSapiV1MarginIsolatedMarginTierResponseBody200LiquidationRiskRatio = GHC.Maybe.Nothing,
      getSapiV1MarginIsolatedMarginTierResponseBody200QuoteAssetMaxBorrowable = GHC.Maybe.Nothing,
      getSapiV1MarginIsolatedMarginTierResponseBody200Symbol = GHC.Maybe.Nothing,
      getSapiV1MarginIsolatedMarginTierResponseBody200Tier = GHC.Maybe.Nothing
    }

-- | > GET /sapi/v1/margin/isolatedMarginTier
--
-- The same as 'getSapiV1MarginIsolatedMarginTier' but accepts an explicit configuration.
getSapiV1MarginIsolatedMarginTierWithConfiguration ::
  forall m.
  Binance.Common.MonadHTTP m =>
  -- | The configuration to use in the request
  Binance.Common.Configuration ->
  -- | Contains all available parameters of this operation (query and path parameters)
  GetSapiV1MarginIsolatedMarginTierParameters ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response GetSapiV1MarginIsolatedMarginTierResponse)
getSapiV1MarginIsolatedMarginTierWithConfiguration
  config
  parameters =
    GHC.Base.fmap
      ( \response_4 ->
          GHC.Base.fmap
            ( Data.Either.either GetSapiV1MarginIsolatedMarginTierResponseError GHC.Base.id
                GHC.Base.. ( \response body ->
                               if
                                   | (\status_5 -> Network.HTTP.Types.Status.statusCode status_5 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) ->
                                     GetSapiV1MarginIsolatedMarginTierResponse200
                                       Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                            Data.Either.Either
                                                              GHC.Base.String
                                                              ([GetSapiV1MarginIsolatedMarginTierResponseBody200])
                                                        )
                                   | (\status_6 -> Network.HTTP.Types.Status.statusCode status_6 GHC.Classes.== 400) (Network.HTTP.Client.Types.responseStatus response) ->
                                     GetSapiV1MarginIsolatedMarginTierResponse400
                                       Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                            Data.Either.Either
                                                              GHC.Base.String
                                                              Error
                                                        )
                                   | (\status_7 -> Network.HTTP.Types.Status.statusCode status_7 GHC.Classes.== 401) (Network.HTTP.Client.Types.responseStatus response) ->
                                     GetSapiV1MarginIsolatedMarginTierResponse401
                                       Data.Functor.<$> ( Data.Aeson.eitherDecodeStrict body ::
                                                            Data.Either.Either
                                                              GHC.Base.String
                                                              Error
                                                        )
                                   | GHC.Base.otherwise -> Data.Either.Left "Missing default response type"
                           )
                  response_4
            )
            response_4
      )
      ( Binance.Common.doCallWithConfiguration
          config
          (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET")
          (Data.Text.pack "/sapi/v1/margin/isolatedMarginTier")
          [ Binance.Common.QueryParameter (Data.Text.pack "symbol") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQuerySymbol parameters)) (Data.Text.pack "form") GHC.Types.False,
            Binance.Common.QueryParameter (Data.Text.pack "tier") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> getSapiV1MarginIsolatedMarginTierParametersQueryTier parameters) (Data.Text.pack "form") GHC.Types.False,
            Binance.Common.QueryParameter (Data.Text.pack "recvWindow") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> getSapiV1MarginIsolatedMarginTierParametersQueryRecvWindow parameters) (Data.Text.pack "form") GHC.Types.False,
            Binance.Common.QueryParameter (Data.Text.pack "timestamp") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp parameters)) (Data.Text.pack "form") GHC.Types.False,
            Binance.Common.QueryParameter (Data.Text.pack "signature") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQuerySignature parameters)) (Data.Text.pack "form") GHC.Types.False
          ]
      )

-- | > GET /sapi/v1/margin/isolatedMarginTier
--
-- The same as 'getSapiV1MarginIsolatedMarginTier' but returns the raw 'Data.ByteString.Char8.ByteString'.
getSapiV1MarginIsolatedMarginTierRaw ::
  forall m.
  Binance.Common.MonadHTTP m =>
  -- | Contains all available parameters of this operation (query and path parameters)
  GetSapiV1MarginIsolatedMarginTierParameters ->
  -- | Monadic computation which returns the result of the operation
  Binance.Common.ClientT m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString)
getSapiV1MarginIsolatedMarginTierRaw parameters =
  GHC.Base.id
    ( Binance.Common.doCallWithConfigurationM
        (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET")
        (Data.Text.pack "/sapi/v1/margin/isolatedMarginTier")
        [ Binance.Common.QueryParameter (Data.Text.pack "symbol") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQuerySymbol parameters)) (Data.Text.pack "form") GHC.Types.False,
          Binance.Common.QueryParameter (Data.Text.pack "tier") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> getSapiV1MarginIsolatedMarginTierParametersQueryTier parameters) (Data.Text.pack "form") GHC.Types.False,
          Binance.Common.QueryParameter (Data.Text.pack "recvWindow") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> getSapiV1MarginIsolatedMarginTierParametersQueryRecvWindow parameters) (Data.Text.pack "form") GHC.Types.False,
          Binance.Common.QueryParameter (Data.Text.pack "timestamp") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp parameters)) (Data.Text.pack "form") GHC.Types.False,
          Binance.Common.QueryParameter (Data.Text.pack "signature") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQuerySignature parameters)) (Data.Text.pack "form") GHC.Types.False
        ]
    )

-- | > GET /sapi/v1/margin/isolatedMarginTier
--
-- The same as 'getSapiV1MarginIsolatedMarginTier' but accepts an explicit configuration and returns the raw 'Data.ByteString.Char8.ByteString'.
getSapiV1MarginIsolatedMarginTierWithConfigurationRaw ::
  forall m.
  Binance.Common.MonadHTTP m =>
  -- | The configuration to use in the request
  Binance.Common.Configuration ->
  -- | Contains all available parameters of this operation (query and path parameters)
  GetSapiV1MarginIsolatedMarginTierParameters ->
  -- | Monadic computation which returns the result of the operation
  m (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString)
getSapiV1MarginIsolatedMarginTierWithConfigurationRaw
  config
  parameters =
    GHC.Base.id
      ( Binance.Common.doCallWithConfiguration
          config
          (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET")
          (Data.Text.pack "/sapi/v1/margin/isolatedMarginTier")
          [ Binance.Common.QueryParameter (Data.Text.pack "symbol") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQuerySymbol parameters)) (Data.Text.pack "form") GHC.Types.False,
            Binance.Common.QueryParameter (Data.Text.pack "tier") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> getSapiV1MarginIsolatedMarginTierParametersQueryTier parameters) (Data.Text.pack "form") GHC.Types.False,
            Binance.Common.QueryParameter (Data.Text.pack "recvWindow") (Data.Aeson.Types.ToJSON.toJSON Data.Functor.<$> getSapiV1MarginIsolatedMarginTierParametersQueryRecvWindow parameters) (Data.Text.pack "form") GHC.Types.False,
            Binance.Common.QueryParameter (Data.Text.pack "timestamp") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQueryTimestamp parameters)) (Data.Text.pack "form") GHC.Types.False,
            Binance.Common.QueryParameter (Data.Text.pack "signature") (GHC.Maybe.Just GHC.Base.$ Data.Aeson.Types.ToJSON.toJSON (getSapiV1MarginIsolatedMarginTierParametersQuerySignature parameters)) (Data.Text.pack "form") GHC.Types.False
          ]
      )
